ApteanClinic/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ApteanClinic.BusinessLayer;
using ApteanClinic.Filters;
using ApteanClinic.Models;
using Models.Enum;
using Logger;
namespace ApteanClinic.Controllers
{
    [AuthenticateUser]
    [OutputCache(Duration =0)]
    public class AppointmentController : Controller
    {
        private Appointment appointment;
        private AppointmentBusinessLayer appointmentBusinessLayer;
        private DoctorBusinessLayer doctorBusinessLayer;
        private PatientBusinessLayer patientBusinessLayer;
        private AppointmentListViewModel appointmentListViewModel;
        private static int patientId;


        public AppointmentController()
        {
            appointment = new Appointment();
            appointmentListViewModel = new AppointmentListViewModel();
            appointmentBusinessLayer = new AppointmentBusinessLayer();
            patientBusinessLayer = new PatientBusinessLayer();
            doctorBusinessLayer = new DoctorBusinessLayer();
        }

        // GET: Default
        [AuthorizeUser(Roles = "Nurse, Patient")]
       // [CheckId]
        public ActionResult Index(int? id)
        {
            try
            {
                patientId = (int)id;
                return View("Index");
                throw new Exception();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error400");
            }
        }


        [HttpPost]
        public ActionResult Index(AppointmentViewModel appointmentViewModel)
        {
            try
            {
                appointmentBusinessLayer = new AppointmentBusinessLayer();
                Dictionary<string, string> errorMsg = appointmentBusinessLayer.ValidateAppointment(appointmentViewModel);
                if (errorMsg != null)
                {
                    ModelState.AddModelError(errorMsg.ElementAt(0).Key, errorMsg.ElementAt(0).Value);
                    return View("Index");
                }
                appointmentViewModel.PatientId = patientId;
                Dictionary<string, string> errMsg = appointmentBusinessLayer.FixAppointment(appointmentViewModel);

                if (errMsg != null)
                {
                    ModelState.AddModelError(errMsg.ElementAt(0).Key, errMsg.ElementAt(0).Value);
                }
                else
                {
                    Logging.loggInfo($"Appointment is added for patient id {appointmentViewModel.PatientId} with Doctor ID {appointmentViewModel.DoctorId } on date {appointmentViewModel.AppointmentDate } at time {appointmentViewModel.TimeSlot }");
                    if ((int)Session["Role"] == 3)
                        return Redirect("/Patients/Details/" + patientId);
                    else
                        return Redirect("/Appointment/AppointmentList");
                }
                return new HttpNotFoundResult();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error");
            }
        }
        [AuthorizeUser(Roles = "Doctor, Patient")]
        [CheckId]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            appointment = appointmentBusinessLayer.GetAppointmentById(id);
            appointmentListViewModel.Id = appointment.Id;
            appointmentListViewModel.PatientName = patientBusinessLayer.GetPatientNameById(appointment.PatientId);
            appointmentListViewModel.DoctorName = doctorBusinessLayer.GetDoctorNameById(appointment.DoctorId);
            appointmentListViewModel.Date = appointment.Date.ToString().Split(' ')[0];
            appointmentListViewModel.Time = TimeSlots.Timings[appointment.Time];
            appointmentListViewModel.Status = appointment.Status;
            return View(appointmentListViewModel);
        }

        public ActionResult Edit(AppointmentListViewModel appointmentListViewModel)
        {
            int isAppointmentEdited = appointmentBusinessLayer.EditAppointment(appointmentListViewModel, (int)Session["Role"]);

            if (isAppointmentEdited != 0)
            {
                if ((int)Session["Role"] == 1)
                {
                    Logging.loggInfo($"Appointment  status id updated for appointment id { appointmentListViewModel.Id} having  patient id {appointmentListViewModel.PatientId} by Doctor as {appointmentListViewModel.Status}");
                    return Redirect("/Doctors/Details/" + isAppointmentEdited.ToString());
                }
                else if ((int)Session["Role"] == 3)
                {
                    Logging.loggInfo($"Appointment  status id updated for appointment id { appointmentListViewModel.Id} having  patient id {appointmentListViewModel.PatientId} by Patient as {appointmentListViewModel.Status}");
                    return RedirectToAction("/Appointmentlist/" + (int)Session["userid"]);
                }
                return new HttpNotFoundResult();
            }          
            else return new HttpNotFoundResult();
        }

        public ActionResult ShowDoctorData(string specVal)
        {
            var docList = doctorBusinessLayer.GetDoctorsBySpeciality(specVal).ToList();
            return Json(docList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ShowDoctorTime(string doctor, string date)
        {
            var DoctorTimeSlotList = doctorBusinessLayer.GetDoctorAvailableTimeSlots(doctor, date);
            return Json(DoctorTimeSlotList, JsonRequestBehavior.AllowGet);
        }

        [AuthorizeUser(Roles ="Nurse,Patient,Doctor")]
        [CheckId]
        public ActionResult AppointmentList(int? id)
        {
            return View(appointmentBusinessLayer.GetAppointmentListView(id));
        }


        public void ChangeAppointmentStatus(int appointmentId)
        {
            Boolean isStatausChanged = appointmentBusinessLayer.ChangeAppointmentStatus(appointmentId);
        }
    }
}

ApteanClinic/Controllers/MedicalHistoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ApteanClinic.Database;
using ApteanClinic.Models;
using ApteanClinic.BusinessLayer;
using BusinessLayer;
using log4net;
using ApteanClinic.Filters;
using Logger;
namespace ApteanClinic.Controllers
{
    [AuthenticateUser]
    [OutputCache(Duration = 0)]
    public class MedicalHistoriesController : Controller
    {
        private static int patientId;
        private static int? appointmentId = null;
        private MedicalHistoriesBusinessLayer medicalHistoriesBusinessLayer;

        // GET: MedicalHistories
        [AuthorizeUser(Roles = "Doctor, Nurse, Admin")]
        public ActionResult Index()
        {
            medicalHistoriesBusinessLayer = new MedicalHistoriesBusinessLayer();
            Logging.loggInfo($"Showing list of all medical histories");
            return View(medicalHistoriesBusinessLayer.GetMedicalHistory(null));

        }

        [AuthorizeUser(Roles = "Admin,Nurse,Doctor,Patient")]
        [CheckId]
        // GET: MedicalHistories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return Redirect("/Error/Index?error=400");
            }

            medicalHistoriesBusinessLayer = new MedicalHistoriesBusinessLayer();
            var history = medicalHistoriesBusinessLayer.GetMedicalHistory(id);
            if (history == null)
            {
                Logging.loggError($"No Patient found having nurse id = {id}");
                return Redirect("/Error/Index");
            }
            Logging.loggInfo($"Showing Medical history of Patient having id = {id}");
            return View(history);

        }

        [AuthorizeUser(Roles = "Doctor,Nurse")]
        // GET: MedicalHistories/Create
        public ActionResult Create(int id, int? aid)
        {

            patientId = id;
            if (aid != null)
            {
                appointmentId = aid;
            }
            return View();
        }

        // POST: MedicalHistories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MedicalHistory medicalHistory)
        {
            if (ModelState.IsValid)
            {
                MedicalHistoriesBusinessLayer businessLayer = new MedicalHistoriesBusinessLayer();
                if (appointmentId != null)
                {
                    medicalHistory.AppointmentId = (int)appointmentId;
                    AppointmentBusinessLayer appointmentBusinessLayer = new AppointmentBusinessLayer();
                    appointmentBusinessLayer.ChangeAppointmentStatus(medicalHistory.AppointmentId);
                }
                medicalHistory.PatientId = patientId;
                businessLayer.AddHistory(medicalHistory);
                Logging.loggInfo($"Medcial history added  of the patient having patient id = {medicalHistory.PatientId}");
                return Redirect("/Patients/Details/" + patientId);
            }
            return View(medicalHistory);
        }

        protected override void Dispose(bool disposing)
        {
            medicalHistoriesBusinessLayer = new MedicalHistoriesBusinessLayer();
            if (disposing)
            {
                medicalHistoriesBusinessLayer.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ApteanClinic/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ApteanClinic.BusinessLayer;
using ApteanClinic.Database;
using ApteanClinic.Filters;
using ApteanClinic.Models;
using Logger;

namespace ApteanClinic.Controllers
{
    [OutputCache(Duration = 0)]
    [AuthenticateUser]
    public class PatientsController : Controller
    {
        private PatientBusinessLayer patientBusinessLayer = new PatientBusinessLayer();
        // GET: Patients

        [AuthorizeUser(Roles = "Admin,Doctor,Nurse")]
        public ActionResult Index()
        {
            var patients = patientBusinessLayer.GetAllPatients(Session["Role"].ToString(),int.Parse(Session["UserId"].ToString()));
            Logging.loggInfo("Showing list of all patients to user");
            return View(patients.ToList());
        }

        [CheckId]
        // GET: Patients/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return Redirect("/Error/Index?error=400");
            }
            Patient patient = patientBusinessLayer.GetPatientById((int)id);
            if (patient == null)
            {
                Logging.loggError($"No Patient found having Patient id = {id}");
                return Redirect("/Error/Index");
            }
            Logging.loggInfo($"Showing results of patient having patient id = {id} and Name = {patient.PatientUser.Name}");
            return View(patient);
        }

        [AuthorizeUser(Roles ="Admin,Nurse")]
        // GET: Patients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Patient patient)
        {
            if (!ModelState.IsValid)
            {
                return View(patient);
            }
            if(!UserDataLayer.CheckEmail(patient.PatientUser.Email))
            {
                ModelState.AddModelError("PatientUser.Email", "Email already exists");
                return View(patient);
            }
            patient.PatientUser.Role = Models.Enum.Role.Patient;
            patientBusinessLayer.AddPatient(patient);
            
            Logging.loggInfo($"Patient addedd with User id = {patient.PatientUser.Id} and Name = {patient.PatientUser.Name}");
            return RedirectToAction("Index");
        }

        // GET: Patients/Edit/5
        [AuthorizeUser(Roles ="Admin,Patient")]
        [CheckId]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return Redirect("/Error/Index?error=400");
            }
            Patient patient = patientBusinessLayer.GetPatientById((int)id);
            if (patient == null)
            {
                Logging.loggError($"No Patient found having Patient id = {id}");
                return Redirect("/Error/Index");
            }
            return View(patient);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Patient patient)
        {
            if (ModelState.IsValid)
            {
                patientBusinessLayer.UpdatePatientDetials(patient);
                Logging.loggInfo($"Patient Edited with id = {patient.Id}");
                return RedirectToAction("Details/" + patient.Id);
            }
            return View(patient);
        }

        // GET: Patients/Delete/5
        [AuthorizeUser(Roles ="Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return Redirect("/Error/Index?error=400");
            }
            Patient patient = patientBusinessLayer.GetPatientById((int)id);
            if (patient == null)
            {
                Logging.loggError($"No Patient found having Patient id = {id}");
                return Redirect("/Error/Index");
            }
            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Patient patient = patientBusinessLayer.GetPatientById((int)id);
            patientBusinessLayer.RemovePatient(patient);
            Logging.loggInfo($"Patient delted having patient id = {id}");
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                patientBusinessLayer.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ApteanClinic/Views/Patients/Create.cshtml
@model ApteanClinic.Models.Patient

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Add Patient</h2>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.PatientUser.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PatientUser.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientUser.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientUser.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EnumDropDownListFor(model => model.PatientUser.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PatientUser.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientUser.BloodGroup, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EnumDropDownListFor(model => model.PatientUser.BloodGroup, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PatientUser.BloodGroup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientUser.Contact, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PatientUser.Contact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientUser.Contact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientUser.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PatientUser.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientUser.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientUser.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PatientUser.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientUser.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientUser.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.PatientUser.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientUser.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EmergengyContactName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.EmergengyContactName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmergengyContactName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EmergencyContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.EmergencyContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmergencyContactNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group text-center">
            <input type="submit" value="Add Patient" class="btn btn-success" />
        </div>
    </div>
}

ApteanClinic/Views/Patients/Delete.cshtml
@model ApteanClinic.Models.Patient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Patient</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PatientUser.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientUser.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientUser.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientUser.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientUser.BloodGroup)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientUser.BloodGroup)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientUser.Contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientUser.Contact)
        </dd>

        @Html.HiddenFor(model => model.PatientUser.Password)

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ApteanClinic/Views/Patients/Details.cshtml
@model ApteanClinic.Models.Patient
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/HomePageLayout.cshtml";
}

<link rel="stylesheet" href="~/Content/Details.css" />

<h3>Patient's Details</h3>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">

            <div class="detailsShow">
                <div class="x_content">
                    <div class="col-md-3 col-sm-3 col-xs-12 profile_left ">
                        <div class="profile_img">
                            <div id="crop-avatar">
                                <img class="img-responsive avatar-view" src="~/Images/user.png">
                            </div>
                        </div>

                        <h3> @Html.DisplayFor(model => model.PatientUser.Name)</h3>
                        <ul class="list-unstyled user_data">
                            <li class="details-list"> <i class="glyphicon glyphicon-user"><strong>@Html.DisplayNameFor(model => model.Id) : </strong> @Html.DisplayFor(model => model.Id)</i></li>
                            <li class="details-list"> <i class="glyphicon glyphicon-user"><strong>@Html.DisplayNameFor(model => model.PatientUser.Gender) : </strong> @Html.DisplayFor(model => model.PatientUser.Gender)</i></li>
                            <li class="details-list"> <i class="glyphicon glyphicon-user"><strong>@Html.DisplayNameFor(model => model.Height) : </strong> @Html.DisplayFor(model => model.Height)</i></li>
                            <li class="details-list"> <i class="glyphicon glyphicon-user"><strong>@Html.DisplayNameFor(model => model.Weight) : </strong> @Html.DisplayFor(model => model.Weight)</i></li>
                            <li class="details-list"> <i class="glyphicon glyphicon-map-marker user-profile-icon"></i><strong>Address :</strong> @Html.DisplayFor(model => model.Address)</li>
                            <li class="details-list"> <i class="glyphicon glyphicon-earphone"></i><strong>@Html.DisplayNameFor(model => model.PatientUser.Contact) :</strong> @Html.DisplayFor(model => model.PatientUser.Contact)</li>
                            <li class="details-list"> <strong>@Html.DisplayNameFor(model => model.EmergengyContactName) :</strong> @Html.DisplayFor(model => model.EmergengyContactName) </li>
                            <li class="details-list"> <i class="glyphicon glyphicon-phone-alt"></i><strong>>@Html.DisplayNameFor(model => model.EmergencyContactNumber) :</strong> @Html.DisplayFor(model => model.EmergencyContactNumber) </li>
                        </ul>
                        @if (Session["Role"].ToString() != "Doctor")
                        {
                            <button class="btn btn-default" type="button" onclick="location.href='@Url.Action("Edit", "Patients", new { id = Model.Id })'"><span style="padding:5px;" class="glyphicon glyphicon-edit"></span>Edit</button>
                            if (Session["Role"].ToString() == "Patient")
                            {
                                <button class="btn btn-default" type="button" onclick="location.href='/ResetPassword/Index'"><i style="padding:5px" class="fa fa-lock"></i> Reset Password </button>
                            }
                        }
                        <br />
                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <span class="section" style="font-size:x-large"> Appointment</span>
                            <br /> <br />
                            <h4>
                                <a href="@Url.Action("AppointmentList", "Appointment", new {id = Model.Id})">Patient Appointment </a>
                            </h4>

                            </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <span class="section" style="font-size:x-large">Patient's Medical History </span>
                            <br />
                            <br />
                            <h4>
                                <a href="@Url.Action("Details", "MEdicalHistories", new {id = Model.Id})">Medical History</a>&nbsp;
                                @if ((int)Session["Role"] == 1)
                                {
                                    <a href="@Url.Action("Create", "MedicalHistories", new { id = Model.Id })"><i class="fa fa-plus"></i></a>
                                }

                            </h4>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ApteanClinic/Views/Patients/Index.cshtml
@model IEnumerable<ApteanClinic.Models.Patient>

@{
    ViewBag.Title = "Index";
}

<h1>Patients</h1>

<div class="tables row">
        @Html.Partial("_PatientList", Model)
</div>

ApteanClinic/Views/Patients/_PatientList.cshtml
@model IEnumerable<ApteanClinic.Models.Patient>
<html>
<head>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" cellspacing="0">
</head>
<body>

    <table id="myTable" class="table table-striped table-bordered table-sm">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PatientUser.Id)
                    <i class="fa fa-fw fa-sort"></i>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PatientUser.Name)
                    <i class="fa fa-fw fa-sort"></i>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PatientUser.Contact)
                    <i class="fa fa-fw fa-sort"></i>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PatientUser.Email)
                    <i class="fa fa-fw fa-sort"></i>
                </th>
                <th>
                    @if (Session["Role"].ToString() == "Admin" || Session["Role"].ToString() == "Nurse")
                    {
                        <button class="btn btn-primary" type="button" onclick="location.href='@Url.Action("Create", "Patients")'"><span style="padding:5px;" class="glyphicon glyphicon-plus-sign"></span>Add Patient</button>
                    }
                </th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PatientUser.Id)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PatientUser.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PatientUser.Contact)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PatientUser.Email)
                    </td>
                    <td>
                        @if (Session["Role"].ToString() == "Nurse" || Session["Role"].ToString() == "Patient")
                        {
                            <button class="btn btn-info" type="button" onclick="location.href='@Url.Action("Index", "Appointment", new { id = item.Id })'"><span style="padding:5px;" class="glyphicon glyphicon-pencil"></span>Fix Appointment</button>
                        }
                        <button class="btn btn-default" onclick="location.href='@Url.Action("Details", "Patients", new { id = item.Id })'" type="button"><span style="padding:5px;" class="glyphicon glyphicon-folder-close"></span>Details</button>
                        @if (Session["Role"].ToString() == "Admin")
                        {
                            <button class="btn btn-danger" type="button" onclick="location.href='@Url.Action("Delete", "Patients", new { id = item.Id })'"><span style="padding:5px;" class="glyphicon glyphicon-trash"></span>Delete</button>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>