ApteanClinic/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ApteanClinic.BusinessLayer;
using ApteanClinic.Filters;
using ApteanClinic.Models;
using Models.Enum;
using Logger;
namespace ApteanClinic.Controllers
{
    [AuthenticateUser]
    [OutputCache(Duration =0)]
    public class AppointmentController : Controller
    {
        private Appointment appointment;
        private AppointmentBusinessLayer appointmentBusinessLayer;
        private DoctorBusinessLayer doctorBusinessLayer;
        private PatientBusinessLayer patientBusinessLayer;
        private AppointmentListViewModel appointmentListViewModel;
        private static int patientId;


        public AppointmentController()
        {
            appointment = new Appointment();
            appointmentListViewModel = new AppointmentListViewModel();
            appointmentBusinessLayer = new AppointmentBusinessLayer();
            patientBusinessLayer = new PatientBusinessLayer();
            doctorBusinessLayer = new DoctorBusinessLayer();
        }

        // GET: Default
        [AuthorizeUser(Roles = "Nurse, Patient")]
       // [CheckId]
        public ActionResult Index(int? id)
        {
            try
            {
                patientId = (int)id;
                return View("Index");
                throw new Exception();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error400");
            }
        }


        [HttpPost]
        public ActionResult Index(AppointmentViewModel appointmentViewModel)
        {
            try
            {
                appointmentBusinessLayer = new AppointmentBusinessLayer();
                Dictionary<string, string> errorMsg = appointmentBusinessLayer.ValidateAppointment(appointmentViewModel);
                if (errorMsg != null)
                {
                    ModelState.AddModelError(errorMsg.ElementAt(0).Key, errorMsg.ElementAt(0).Value);
                    return View("Index");
                }
                appointmentViewModel.PatientId = patientId;
                Dictionary<string, string> errMsg = appointmentBusinessLayer.FixAppointment(appointmentViewModel);

                if (errMsg != null)
                {
                    ModelState.AddModelError(errMsg.ElementAt(0).Key, errMsg.ElementAt(0).Value);
                }
                else
                {
                    Logging.loggInfo($"Appointment is added for patient id {appointmentViewModel.PatientId} with Doctor ID {appointmentViewModel.DoctorId } on date {appointmentViewModel.AppointmentDate } at time {appointmentViewModel.TimeSlot }");
                    if ((int)Session["Role"] == 3)
                        return Redirect("/Patients/Details/" + patientId);
                    else
                        return Redirect("/Appointment/AppointmentList");
                }
                return new HttpNotFoundResult();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error");
            }
        }
        [AuthorizeUser(Roles = "Doctor, Patient")]
        [CheckId]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            appointment = appointmentBusinessLayer.GetAppointmentById(id);
            appointmentListViewModel.Id = appointment.Id;
            appointmentListViewModel.PatientName = patientBusinessLayer.GetPatientNameById(appointment.PatientId);
            appointmentListViewModel.DoctorName = doctorBusinessLayer.GetDoctorNameById(appointment.DoctorId);
            appointmentListViewModel.Date = appointment.Date.ToString().Split(' ')[0];
            appointmentListViewModel.Time = TimeSlots.Timings[appointment.Time];
            appointmentListViewModel.Status = appointment.Status;
            return View(appointmentListViewModel);
        }

        public ActionResult Edit(AppointmentListViewModel appointmentListViewModel)
        {
            int isAppointmentEdited = appointmentBusinessLayer.EditAppointment(appointmentListViewModel, (int)Session["Role"]);

            if (isAppointmentEdited != 0)
            {
                if ((int)Session["Role"] == 1)
                {
                    Logging.loggInfo($"Appointment  status id updated for appointment id { appointmentListViewModel.Id} having  patient id {appointmentListViewModel.PatientId} by Doctor as {appointmentListViewModel.Status}");
                    return Redirect("/Doctors/Details/" + isAppointmentEdited.ToString());
                }
                else if ((int)Session["Role"] == 3)
                {
                    Logging.loggInfo($"Appointment  status id updated for appointment id { appointmentListViewModel.Id} having  patient id {appointmentListViewModel.PatientId} by Patient as {appointmentListViewModel.Status}");
                    return RedirectToAction("/Appointmentlist/" + (int)Session["userid"]);
                }
                return new HttpNotFoundResult();
            }          
            else return new HttpNotFoundResult();
        }

        public ActionResult ShowDoctorData(string specVal)
        {
            var docList = doctorBusinessLayer.GetDoctorsBySpeciality(specVal).ToList();
            return Json(docList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ShowDoctorTime(string doctor, string date)
        {
            var DoctorTimeSlotList = doctorBusinessLayer.GetDoctorAvailableTimeSlots(doctor, date);
            return Json(DoctorTimeSlotList, JsonRequestBehavior.AllowGet);
        }

        [AuthorizeUser(Roles ="Nurse,Patient,Doctor")]
        [CheckId]
        public ActionResult AppointmentList(int? id)
        {
            return View(appointmentBusinessLayer.GetAppointmentListView(id));
        }


        public void ChangeAppointmentStatus(int appointmentId)
        {
            Boolean isStatausChanged = appointmentBusinessLayer.ChangeAppointmentStatus(appointmentId);
        }
    }
}

ApteanClinic/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ApteanClinic.BusinessLayer;
using ApteanClinic.Database;
using ApteanClinic.Filters;
using ApteanClinic.Models;
using log4net;
using Models.Enum;
using Logger;

namespace ApteanClinic.Controllers
{
    [OutputCache(Duration = 0)]
    [AuthenticateUser]
    public class DoctorsController : Controller
    {
        private ApteanClinicContext db = new ApteanClinicContext();
        public Doctor Doctor;
        private DoctorBusinessLayer doctorBusinessLayer;
        private UserBusinessLayer userBusinessLayer;

        private AppointmentViewModel appointmentViewModel;
        private PatientBusinessLayer patientBusinessLayer;
        private DoctorDetailsViewModel doctorDetailsViewModel;

        public DoctorsController()
        {
            userBusinessLayer = new UserBusinessLayer();
            appointmentViewModel = new AppointmentViewModel();
            doctorBusinessLayer = new DoctorBusinessLayer();
            patientBusinessLayer = new PatientBusinessLayer();
        }

        [AuthorizeUser(Roles = "Admin,Nurse")]
        // GET: Doctors
        public ActionResult Index()
        {
            var doctors = doctorBusinessLayer.GetAllDoctors();
            return View(doctors.ToList());
        }

        [HttpPost]
        public ActionResult GetPartial(string searchTerm = null)
        {

            var doctors = doctorBusinessLayer.GetAllDoctors();
            return View("Index", doctors);

        }
        [AuthorizeUser(Roles = "Admin,Nurse,Doctor")]
        [CheckId]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return Redirect("/Error/Index?error=400");
            }
            doctorDetailsViewModel = new DoctorDetailsViewModel();
            doctorDetailsViewModel = doctorBusinessLayer.GetDoctorDetials((int)id);
            return View(doctorDetailsViewModel);
        }

        [AuthorizeUser(Roles = "Admin")]
        // GET: Doctors/Create
        public ActionResult Create()
        { 
            DoctorDetailsViewModel doctorDetailsViewModel = new DoctorDetailsViewModel();
            doctorDetailsViewModel.Doctor = new Doctor();
            doctorDetailsViewModel.Doctor.DoctorUser = new User();
            doctorDetailsViewModel.Doctor.ShiftTime = new List<DoctorTime>();
            doctorDetailsViewModel.Timings = new List<SelectListItem>();
            for (int i = 0; i < TimeSlots.Timings.Count; i++)
            {
                doctorDetailsViewModel.Timings.Add(
                    new SelectListItem
                    {
                        Text = TimeSlots.Timings[i],
                        Value = i.ToString(),
                        Selected = false
                    });
            }
            return View(doctorDetailsViewModel);
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DoctorDetailsViewModel doctorDetailsViewModel)
        {
            doctorBusinessLayer = new DoctorBusinessLayer();
            userBusinessLayer = new UserBusinessLayer();
            var user = userBusinessLayer.GetUserByEmail(doctorDetailsViewModel.Doctor.DoctorUser.Email);
            if (user != null)
            {
                ModelState.AddModelError("DoctorUser.Email", "Email already exists");
                return View(doctorDetailsViewModel);
            }
            Doctor doctor = new Doctor();
            doctor.ShiftTime = new List<DoctorTime>();
            doctor = doctorDetailsViewModel.Doctor;
            doctorBusinessLayer.AddDoctor(doctor,doctorDetailsViewModel.Timings);

            Logging.loggInfo($"Doctor addedd with Userid = {doctor.DoctorUser.Id} and Name = {doctor.DoctorUser.Name} ");
            return RedirectToAction("Index");
        }

        // GET: Doctors/Edit/5
        [AuthorizeUser(Roles = "Admin,Doctor")]
        [CheckId]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return Redirect("/Error/Index?error=400");
            }
            Doctor doctor = doctorBusinessLayer.GetDoctorById((int)id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Doctor doctor)
        {
           // doctor.ShiftTime = doctorBusinessLayer.GetDoctorShiftTimeByDoctorId(doctor.Id);
            if (ModelState.IsValid)
            {
                doctorBusinessLayer.EditDoctorDetails(doctor);
                ViewBag.UserId = new SelectList(db.Users, "Id", "Name", doctor.DoctorUser.Id);
                return RedirectToAction("Details/" + doctor.Id);
            }
            return View(doctor);
        }

        // GET: Doctors/Delete/5
        [AuthorizeUser(Roles ="Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return Redirect("/Error/Index?error=400");
            }

            Doctor doctor = doctorBusinessLayer.GetDoctorById((int)id);

            if (doctor == null)
            {
                Logging.loggError($"No Doctor found having Doctor id = {id}");
                return HttpNotFound();
            }
            
            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            Logging.loggInfo($"Doctor deleted haiving doctor Id = {id}");
            doctorBusinessLayer.DeleteDoctor(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [AuthorizeUser(Roles ="Admin,Doctor,Nurse")]
        
        public ActionResult GetDoctorAppointments(int docId, int appointments)
        {
            doctorBusinessLayer = new DoctorBusinessLayer();
            if (appointments == 0)
            {
                List<DoctorAppointment> doctorAppointments = doctorBusinessLayer.GetDoctorsUpcomingAppointments(docId);
                return Json(doctorAppointments, JsonRequestBehavior.AllowGet);
            }
            else
            {
                List<DoctorAppointment> doctorAppointments = doctorBusinessLayer.GetDoctorsAllAppointments(docId);
                return Json(doctorAppointments, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

ApteanClinic/Controllers/MedicalHistoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ApteanClinic.Database;
using ApteanClinic.Models;
using ApteanClinic.BusinessLayer;
using BusinessLayer;
using log4net;
using ApteanClinic.Filters;
using Logger;
namespace ApteanClinic.Controllers
{
    [AuthenticateUser]
    [OutputCache(Duration = 0)]
    public class MedicalHistoriesController : Controller
    {
        private static int patientId;
        private static int? appointmentId = null;
        private MedicalHistoriesBusinessLayer medicalHistoriesBusinessLayer;

        // GET: MedicalHistories
        [AuthorizeUser(Roles = "Doctor, Nurse, Admin")]
        public ActionResult Index()
        {
            medicalHistoriesBusinessLayer = new MedicalHistoriesBusinessLayer();
            Logging.loggInfo($"Showing list of all medical histories");
            return View(medicalHistoriesBusinessLayer.GetMedicalHistory(null));

        }

        [AuthorizeUser(Roles = "Admin,Nurse,Doctor,Patient")]
        [CheckId]
        // GET: MedicalHistories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return Redirect("/Error/Index?error=400");
            }

            medicalHistoriesBusinessLayer = new MedicalHistoriesBusinessLayer();
            var history = medicalHistoriesBusinessLayer.GetMedicalHistory(id);
            if (history == null)
            {
                Logging.loggError($"No Patient found having nurse id = {id}");
                return Redirect("/Error/Index");
            }
            Logging.loggInfo($"Showing Medical history of Patient having id = {id}");
            return View(history);

        }

        [AuthorizeUser(Roles = "Doctor,Nurse")]
        // GET: MedicalHistories/Create
        public ActionResult Create(int id, int? aid)
        {

            patientId = id;
            if (aid != null)
            {
                appointmentId = aid;
            }
            return View();
        }

        // POST: MedicalHistories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MedicalHistory medicalHistory)
        {
            if (ModelState.IsValid)
            {
                MedicalHistoriesBusinessLayer businessLayer = new MedicalHistoriesBusinessLayer();
                if (appointmentId != null)
                {
                    medicalHistory.AppointmentId = (int)appointmentId;
                    AppointmentBusinessLayer appointmentBusinessLayer = new AppointmentBusinessLayer();
                    appointmentBusinessLayer.ChangeAppointmentStatus(medicalHistory.AppointmentId);
                }
                medicalHistory.PatientId = patientId;
                businessLayer.AddHistory(medicalHistory);
                Logging.loggInfo($"Medcial history added  of the patient having patient id = {medicalHistory.PatientId}");
                return Redirect("/Patients/Details/" + patientId);
            }
            return View(medicalHistory);
        }

        protected override void Dispose(bool disposing)
        {
            medicalHistoriesBusinessLayer = new MedicalHistoriesBusinessLayer();
            if (disposing)
            {
                medicalHistoriesBusinessLayer.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ApteanClinic/Views/Doctors/AppointmentList.cshtml
@model IEnumerable<ApteanClinic.Models.AppointmentListViewModel>

@{
    ViewBag.Title = "AppointmentList";
}

<style>
    .btn-round {
        border-radius: 40px;
        width: 150px;
    }
</style>

<table class="table text-center">
    <tr>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.PatientName)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PatientName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Date)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Time)
    </td>
    @if (item.Status == ApteanClinic.Models.Enums.AppointmentStatus.Pending)
    {
        <td class="btn btn-warning btn-round">PENDING</td>
        if (((int)Session["Role"] == 1))
        {
            <td><button class="btn btn-primary" onclick="location.href='@Url.Action("Edit", "Appointment", new { id = item.Id })'"><span class="glyphicon glyphicon-pencil" style="padding:3px;"></span>Edit</button></td>
        }
    }
    else if (item.Status == ApteanClinic.Models.Enums.AppointmentStatus.Approved)
    {
        <td class="btn btn-success btn-round">APPROVED</td>
        if (((int)Session["Role"] == 1))
        {
            <td><button class="btn btn-default" onclick="location.href='@Url.Action("Create", "MedicalHistories", new { id = item.PatientId, aid = item.Id })'">Add Diagnosis</button></td>
        }
    }
    else if (item.Status == ApteanClinic.Models.Enums.AppointmentStatus.Cancelled)
    {
        <td class="btn btn-danger btn-round">CANCELLED</td>
    }
    else if (item.Status == ApteanClinic.Models.Enums.AppointmentStatus.Closed)
    {
        <div class="btn btn-default btn-round">CLOSED</div>
        if ((int)Session["Role"] == 2 || (int)Session["Role"] == 1)
        {

            <td>
                <div class="btn btn-default btn-round">
                    @Html.ActionLink("Add Medicines", "AddMedicines", "Invoice", new { id = item.Id }, null)
                </div>
            </td>
            <br />



        }
    }
</tr>
        }

</table>

ApteanClinic/Views/Doctors/Delete.cshtml
@model ApteanClinic.Models.Doctor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DoctorUser.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorUser.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Speciality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Speciality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fees)
        </dt>
        @Html.HiddenFor(model => model.DoctorUser.Password)
        @Html.HiddenFor(model => model.DoctorUser.Id)
        <dd>
            @Html.DisplayFor(model => model.Fees)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorUser.Contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorUser.Contact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorUser.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorUser.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorUser.BloodGroup)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorUser.BloodGroup)
        </dd>

        
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ApteanClinic/Views/Doctors/Details.cshtml
@model ApteanClinic.Models.DoctorDetailsViewModel
@{
    ViewBag.Title = "Details";
}

<link rel="stylesheet" href="~/Content/Details.css" />
<style>
    /*.table-head {
        font-size: 25px;
        font: bold;
    }

    .table-body {
        font-size: 20px;
    }*/

</style>

<div class="page-title">
    <div class="title_left">
        <h3>Details</h3>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="detailsShow">
                <div class="x_content">
                    <div class="col-md-3 col-sm-3 col-xs-12 profile_left ">
                        <div class="profile_img">
                            <div id="crop-avatar">
                                <img class="img-responsive avatar-view" src="~/Images/user.png">
                            </div>
                        </div>
                        <h3> @Html.DisplayFor(model => model.Doctor.DoctorUser.Name)</h3>
                        <div id="docid" hidden>@Model.Doctor.Id</div>
                        <ul class="list-unstyled user_data" style="font-size:20px">
                            <li> <i class="glyphicon glyphicon-briefcase"> @Html.DisplayFor(model => model.Doctor.Speciality)</i></li>
                            <li> <i class="glyphicon glyphicon-envelope"> @Html.DisplayFor(model => model.Doctor.DoctorUser.Email)</i></li>
                            <li> <i class="glyphicon glyphicon-earphone"> @Html.DisplayFor(model => model.Doctor.DoctorUser.Contact)</i></li>
                            <li style="margin-top:10px"> <span style="padding:7px" class="label label-success"> Available </span> </li>
                        </ul>
                        @if (Session["Role"].ToString() == "Doctor" || Session["Role"].ToString() == "Admin")
                        {
                            <button class="btn btn-default" style="margin-top:10px" type="button" onclick="location.href='@Url.Action("Edit", "Doctors", new { id = Model.Doctor.Id })'"><span style="padding:5px;" class="glyphicon glyphicon-edit"></span>Edit</button>
                        }
                        <br />
                    </div>
                    @if (Session["Role"].ToString() == "Doctor")
                    {
                        <div class="col-md-9 col-sm-9 col-xs-12">
                            <button class="btn btn-lg " id="upcomingappointments">Upcoming Appointments</button>
                            <button class="btn btn-lg " id="allappointments">All</button><br /><br />
                            <table id="appointmenttable" class="table"></table>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript" src="~/Scripts/DoctorDetails.js"></script>
}

ApteanClinic/Views/Doctors/Index.cshtml
@model IEnumerable<ApteanClinic.Models.Doctor>

@{
    ViewBag.Title = "Index";
}
    <h1>Doctors</h1>
    <div class="tables row">
        @Html.Partial("_DoctorsList", Model)
    </div>

ApteanClinic/Views/Doctors/_DoctorsList.cshtml
@model IEnumerable<ApteanClinic.Models.Doctor>

<html>
<head>

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">


</head>
<body>

    <table id="myTable" class="table table-striped table-bordered table-sm" cellspacing="0">
        <thead>

            <tr>

                <th>
                    @Html.DisplayNameFor(model => model.DoctorUser.Name)
                    <i class="fa fa-fw fa-sort"></i>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Speciality)
                    <i class="fa fa-fw fa-sort"></i>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Fees)
                    <i class="fa fa-fw fa-sort"></i>
                </th>
                <th>
                    Status
                </th>
                <th>
                    Account Status
                </th>
                <th>
                    @if (Session["Role"].ToString() == "Admin")
                    {
                        <button class="btn btn-primary" type="button" onclick="location.href='@Url.Action("Create", "Doctors")'"><span style="padding:5px; " class="glyphicon glyphicon-plus-sign"></span>Add Doctor</button>
                    }

                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DoctorUser.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Speciality)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fees)
                    </td>
                    <td>
                        <div class="btn btn-success btn-round">Available</div>
                    </td>
                    <td>
                        <div class="btn btn-success btn-round">Active</div>
                    </td>
                    <td>
                        @if (Session["Role"].ToString() == "Admin")
                        {
                            <button class="btn btn-primary" type="button" onclick="location.href='@Url.Action("Edit", "Doctors", new { id = item.Id })'"><span style="padding:5px;" class="glyphicon glyphicon-edit"></span>Edit</button>
                        }
                        <button class="btn btn-default" type="button" onclick="location.href='@Url.Action("Details", "Doctors", new { id = item.Id })'"><span style="padding:5px;" class="glyphicon glyphicon-folder-close"></span>Details</button>
                        @if (Session["Role"].ToString() == "Admin")
                        {
                            <button class="btn btn-danger" type="button" onclick="location.href='@Url.Action("Delete", "Doctors", new { id = item.Id })'"><span style="padding:5px;" class="glyphicon glyphicon-trash"></span>Delete</button>
                        }
                    </td>
                </tr>

            }
        </tbody>
    </table>

</body>
</html>