ApteanClinic/Controllers/ForgotPasswordController.cs
using ApteanClinic.BusinessLayer;
using ApteanClinic.Filters;
using ApteanClinic.Models;
using log4net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Logger;

namespace ApteanClinic.Controllers
{
    public class ForgotPasswordController : Controller
    {
        private UserBusinessLayer userBusinessLayer;
        private static int GeneratedOTP;
        private static string MobileNumber;
        // GET: ForgotPassword
        public ActionResult Index()
        {
            ViewBag.OTP = "false";
            return View();
        }

        public ActionResult OTPSend(ForgotPassword forgotPassword)
        {
            ModelState.Remove("OTP");
            if (!ModelState.IsValid)
            {
                ViewBag.OTP = "false";
                return View("Index");
            }
            GeneratedOTP = Verify.GetOTP(forgotPassword.MobileNumber);
            MobileNumber = forgotPassword.MobileNumber;
            ViewBag.OTP = "true";
            Logging.loggInfo($"Sending otp to user having mobile number {MobileNumber}");
            return View("Index");
        }

        public ActionResult OTPCheck(ForgotPassword forgotPassword)
        {
            ModelState.Remove("MobileNumber");
            if (!ModelState.IsValid)
            {
                return View("Index");
            }

            if (GeneratedOTP == forgotPassword.OTP)
            {
                Logging.loggInfo($"Otp Matched for mobile number {MobileNumber} , redirecting to ResetPassword Page");
                return RedirectToAction("NewPassword");
            }
            ModelState.AddModelError("OTP", "Wrong OTP");
            ViewBag.OTP = "true";
            Logging.loggError($"Otp not matched for mobile number {MobileNumber}");
            return View("Index");
        }

        public ActionResult NewPassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewPassword(string newpassword, string confirmpassword)
        {
            if(newpassword == "")
            {
                Logging.loggError($"New Password empty error");
                ModelState.AddModelError("", "Please enter a valid password");
                return View();
            }
            else if(newpassword != confirmpassword)
            {
                Logging.loggError($"Password Don't match");
                ModelState.AddModelError("", "Passwords don't match");
                return View();
            }
            userBusinessLayer = new UserBusinessLayer();
            Boolean passwordUpdate = userBusinessLayer.UpdateUserPassword(MobileNumber, newpassword);
            if (passwordUpdate)
            {
                Logging.loggInfo($"Password updated of user having mobile number = {MobileNumber}");
                return Redirect("/Login/Index");
            }
            else
            {
                ViewBag.OTP = "false";
                ModelState.AddModelError("", "Operation failed.Please try again");
                Logging.loggError($"Unable to update password");
                return RedirectToAction("Index");
            }
        }
    }
}

ApteanClinic/Views/ForgotPassword/Index.cshtml
@model ApteanClinic.Models.ForgotPassword

@{
    Layout = "~/Views/Shared/LoginPageLayout.cshtml";
    ViewBag.title = "Forgot Password";
}


    <div class="container-fluid" id="OTP-form" style="padding:20px;">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h3><i class="fa fa-lock fa-4x"></i></h3>
                        <h2 class="text-center" style="padding-top:20px;">Forgot Password?</h2>
                        <p class="text-center">You can reset your password here.</p>
                        <div class="panel-body">
                            @if (ViewBag.OTP == "false")
                            {
                                using (Html.BeginForm("OTPSend", "ForgotPassword"))
                                {
                                    @Html.AntiForgeryToken()
                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="text-dark text-center">Please enter your registered Mobile number</div>
                                    <br />
                                    <div class="form-group text-center">
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="glyphicon glyphicon-phone color-blue"></i></span>
                                            @Html.EditorFor(model => model.MobileNumber, new { htmlAttributes = new { @id = "MobileNumber", @class = "form-control" } })
                                        </div>
                                        @Html.ValidationMessageFor(model => model.MobileNumber, "", new { @class = "text-danger" })
                                    </div>
                                    <input type="submit" value="Send OTP" class="btn btn-success btn-block" />
                                    <input type="button" value="Back" onclick="window.location.href='/Login/Index'" class="btn btn-danger btn-block" style="margin-bottom:20px" />
                                }
                            }
                            else
                            {
                                using (Html.BeginForm("OTPCheck", "ForgotPassword"))
                                {
                                    @Html.AntiForgeryToken()
                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="text-dark text-center">Please the 6 digit OTP here</div>
                                    <br />
                                    <div class="form-group text-center">
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="glyphicon glyphicon-envelope color-blue"></i></span>
                                            @Html.EditorFor(model => model.OTP, new { htmlAttributes = new { @id = "OTP", @class = "form-control text-center", placeholder = "*  *  *  *  *  *" } })
                                        </div>
                                        @Html.ValidationMessageFor(model => model.OTP, "", new { @class = "text-danger" })
                                    </div>
                                    <input type="submit" value="Change Password" class="btn btn-success btn-block" />
                                    <input type="button" value="Back" onclick="window.location.href = '/Login/Index'" class="btn btn-danger btn-block" style="margin-bottom:20px" />
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

ApteanClinic/Views/ForgotPassword/NewPassword.cshtml
@{
    Layout = "~/Views/Shared/LoginPageLayout.cshtml";
    ViewBag.title = "Forgot Password";
}


    <div class="container-fluid" id="OTP-form">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h3><i class="fa fa-lock fa-4x"></i></h3>
                        <form action="/ForgotPassword/NewPassword" method="post">
                            <h2 class="text-center" style="padding-top:20px;" >Forgot Password?</h2>
                            <p class="text-center">You can reset your password here.</p>
                            <div class="text-danger">
                                @Html.ValidationSummary()
                            </div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label>New Password</label>
                                    <input type="password" name="newpassword" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label>Confirm Password</label>
                                    <input type="password" name="confirmpassword" class="form-control" />
                                </div>
                                <button class="btn btn-success btn-block">Change Password</button>
                                <button onclick="window.location.href='/Login/Index'" type="button" class="btn btn-danger btn-block">Back</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>